language: node
node_js: stable
branches:
    only:
    - release
install:
- npm install
script:
- npm run build
after_success:
- echo "success !"
- git add dist
- git commit -m"add dist"
- git push origin release