language: node
node_js: stable
branches:
    only:
    - release
before_install:
- git config --global user.name "djytwy"
- git config --global user.email "676534074@qq.com"
install:
- npm install
script:
- npm run build
after_success:
- echo "success !"
- git add dist
- git commit -m"add dist"
- git push --quiet --force https://$REPO_TOKEN@github.com/djytwy/Vue_myserver.git master