language: node
node_js: stable
services:
    - docker
branches:
    only:
    - master
before_install:
- git config --global user.name "djytwy"
- git config --global user.email "676534074@qq.com"
install:
- npm install
script:
- npm run build
after_success:
# 自动化构建提交
# - git checkout release
# - git branch
# - git add dist
# - git commit -m"[skip ci] travis 自动化构建完成"
# - git push -f "https://${REPO_TOKEN}@github.com/djytwy/Vue_myserver.git" release
- docker build -t djytwy/vue_server .
- docker run -d -p 80:80 djytwy/vue_server
- docker ps -a
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
- docker push djytwy/vue_server:1.0
- echo "build over"